theme: jekyll-theme-cayman
title: Hao Xin's Blog
description: 人生代代无穷已, 江月年年望相似. 不知江月待何人, 但见长江送流水.
encoding: utf-8

page_meta:
  description: Hao Xin's Blog.

author:
  name: Hao Xin
  github: haoxins
  email: haoxinst@gmail.com

highlighter: rouge
markdown: kramdown

defaults:
- scope:
    path: archived-2022
    type: pages
  values:
    sectionid: archived-2022
- scope:
    path: articles
    type: pages
  values:
    sectionid: articles
